export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const QUESTION_REPOSITORY = 'QUESTION_REPOSITORY';
export const USER_ANSWER_REPOSITORY = 'USER_ANSWER_REPOSITORY';
export const UNIT_OF_WORK = 'UNIT_OF_WORK';
export const QUESTION_CONDITION_SERVICE = 'QUESTION_CONDITION_SERVICE';
export const USER_PROFILE_SUMMARY_REPOSITORY = 'USER_PROFILE_SUMMARY_REPOSITORY';
export const OPENAI_PROFILE_SERVICE = 'OPENAI_PROFILE_SERVICE';